### ISSUE TITLE
如何减少打包大小

### ISSUE THREAD

**Issue by mztlive** [monako97/neko-ui#5]
老哥，我在引用这个项目之后index.js多了将近300K的大小，有什么办法可以降低吗？

**Comment by monako97** [comment]
目前只提供了umd的方式, 等后续更新吧, 会支持到按需加载的

**Comment by monako97** [comment]
> 老哥，我在引用这个项目之后index.js多了将近300K的大小，有什么办法可以降低吗？

目前只提供了umd的方式, 等后续更新吧, 会支持到按需加载的

**Comment by monako97** [comment]
> 老哥，我在引用这个项目之后index.js多了将近300K的大小，有什么办法可以降低吗？

更新至 2.5.0 或以上版本可支持按需引入

// 例如
```jsx
import 'neko-ui/es/button';

function Demo(){
    return <n-button>按钮</n-button>
}
```
