### ISSUE TITLE
好像缺少什么swc的东西？

### ISSUE THREAD

**Issue by mztlive** [monako97/neko-ui#6]
yarn dev

X [ERROR] Could not resolve "@swc/helpers/_/_object_without_properties_loose"

    node_modules/neko-ui/es/md/index.js:1:62:
      1 │ ...{_ as e}from"@swc/helpers/_/_extends";import{_ as t}from"@swc/helpers/_/_object_without_properties_loose";import{use as r}from"solid-js/web";import{template as ... 
        ╵                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@swc/helpers/_/_object_without_properties_loose" as external to exclude it
  from the bundle, which will remove this error.

**Comment by monako97** [comment]
> yarn dev
> 
> X [ERROR] Could not resolve "@swc/helpers/_/_object_without_properties_loose"
> 
> ```
> node_modules/neko-ui/es/md/index.js:1:62:
>   1 │ ...{_ as e}from"@swc/helpers/_/_extends";import{_ as t}from"@swc/helpers/_/_object_without_properties_loose";import{use as r}from"solid-js/web";import{template as ... 
>     ╵                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ```
> 
> You can mark the path "@swc/helpers/_/_object_without_properties_loose" as external to exclude it from the bundle, which will remove this error.

更新至 2.5.1
