### ISSUE TITLE
可以加上弹窗吗

### ISSUE THREAD

**Issue by tonghu007** [monako97/neko-ui#7]
可以加上弹窗吗？包括模态窗口，提示框等

**Comment by monako97** [comment]
> 可以加上弹窗吗？包括模态窗口，提示框等

👌, 有空我加一下

**Comment by monako97** [comment]
> 可以加上弹窗吗？包括模态窗口，提示框等

添加了两个简易的模态框和提示通知, 更新到 2.7.0
