### ISSUE TITLE
Cli工具无法使用

### ISSUE THREAD

**Issue by mztlive** [monako97/neko-ui#9]
运行 mo create test-neko-cli 得到如下错误

node:internal/modules/cjs/loader:1149
  const err = new Error(message);
              ^

Error: Cannot find module 'less'
Require stack:
- /home/windows/.nvm/versions/node/v21.6.1/lib/node_modules/@moneko/cli/lib/utils/require.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1149:15)
    at Function.resolve (node:internal/modules/helpers:187:19)
    at file:///home/windows/.nvm/versions/node/v21.6.1/lib/node_modules/@moneko/cli/lib/lessc.js:1:318
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:120:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/windows/.nvm/versions/node/v21.6.1/lib/node_modules/@moneko/cli/lib/utils/require.js'
  ]
}

Node.js v21.6.1

**Comment by monako97** [comment]
> 运行 mo create test-neko-cli 得到如下错误
> 
> node:internal/modules/cjs/loader:1149 const err = new Error(message); ^
> 
> Error: Cannot find module 'less' Require stack:
> 
> * /home/windows/.nvm/versions/node/v21.6.1/lib/node_modules/@moneko/cli/lib/utils/require.js
>   at Module._resolveFilename (node:internal/modules/cjs/loader:1149:15)
>   at Function.resolve (node:internal/modules/helpers:187:19)
>   at file:///home/windows/.nvm/versions/node/v21.6.1/lib/node_modules/@moneko/cli/lib/lessc.js:1:318
>   at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
>   at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
>   at async loadESM (node:internal/process/esm_loader:28:7)
>   at async handleMainPromise (node:internal/modules/run_main:120:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>   '/home/windows/.nvm/versions/node/v21.6.1/lib/node_modules/@moneko/cli/lib/utils/require.js'
>   ]
>   }
> 
> Node.js v21.6.1

更新到 cli 工具 2.14.2 版本及以上
